### ISSUE TITLE
Trained Weights on Huggingface

### ISSUE THREAD

**Issue by Qiwei97** [lhf-labs/finance-news-analysis-bert#9]
Hi, the trained weights do not seem to be accessible on Huggingface Hub. May I check if they will be uploaded? Thank you!

**Comment by asier-gutierrez** [comment]
Dear @Qiwei97 thanks you for your interest in our work.

Currently we can not make the models available. However, these scripts are useful in case you have access to the RavenPack dataset.

Kind regards,
Asier

**Comment by Qiwei97** [comment]
Alright, thank you very much!
